# Generated by Django 5.2 on 2025-04-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='product',
        ),
    ]
